---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
components:
  - ../../components/common
patches:
  - target:
      kind: Namespace
      name: home-assistant
    patch: |
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1enforce
        value: privileged
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1warn
        value: privileged
resources:
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./persistent-volume-claims/ks.yaml
  - ./zigbee2mqtt/ks.yaml