---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
components:
  - ../../components/common
  - ../../components/privileged
resources:
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./persistent-volume-claims/ks.yaml
  - ./zigbee2mqtt/ks.yaml