---
# yaml-language-server: $schema=https://schemas.gallay.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
components:
  - ../../components/common
resources:
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./persistent-volume-claims/ks.yaml
  - ./zigbee2mqtt/ks.yaml