---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
patches:
  - target:
      kind: Namespace
      name: media
    patch: |
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1enforce
        value: privileged
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1warn
        value: privileged
resources:
  - ./secrets/ks.yaml
  - ./database-cluster/ks.yaml
  - ./persistent-volume-claims/ks.yaml
  - ./jackett/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./flood/ks.yaml
  - ./emby/ks.yaml
  - ./plex/ks.yaml
  # - ./jellyfin/ks.yaml