---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./secrets/ks.yaml
  # - ./database-cluster/ks.yaml
  - ./persistent-volume-claims/ks.yaml
  # - ./emby/ks.yaml
  # - ./flood/ks.yaml
  # - ./jackett/ks.yaml
  # - ./jellyseerr/ks.yaml
  # - ./plex/ks.yaml
  # - ./qbittorrent/ks.yaml
  # - ./qui/ks.yaml
  # - ./radarr/ks.yaml
  # - ./sonarr/ks.yaml
  # - ./jellyfin/ks.yaml