---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/postgresql.cnpg.io/database_v1.json

apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-db
spec:
  cluster:
    name: immich-database
  name: ${IMMICH_DATABASE}-db
  owner: ${IMMICH_USERNAME}
  ensure: present
  allowConnections: true
