---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs
spec:
  storageClassName: data-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.84
    path: "/media"
  mountOptions:
    - nfsvers=4.2
    # - nconnect=16
    # - hard
    # - noatime
    # - nodiratime
    # - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nfs
spec:
  storageClassName: data-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
