---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: family-pomaz
spec:
  storageClassName: family-pomaz
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.${SECRET_DOMAIN}
    path: "/media/media/family/Videos/Pomaz"
  mountOptions:
    - vers=4.2
    - rsize=1048576
    - wsize=1048576
    - async
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: family-pomaz
spec:
  storageClassName: family-pomaz
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
