---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - downloads.yaml
  - family-pomaz.yaml
  - kids-movies.yaml
  - kids-tv.yaml
  - movies.yaml
  - music-sound.yaml
  - music-video.yaml
  - tv.yaml


  # - archive/emby.yaml
  # - archive/flood.yaml
  # - archive/jackett.yaml
  # - archive/jellyseerr.yaml
  # - archive/plex.yaml
  # - archive/qbittorrent.yaml
  # - archive/qui.yaml
  # - archive/radarr.yaml
  # - archive/sonarr.yaml