---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - data.yaml
  # - data-nfs.yaml
  - downloads.yaml
  - family-pomaz.yaml
  - kids-movies.yaml
  - kids-tv.yaml
  - movies.yaml
  - music-sound.yaml
  - music-video.yaml
  - tv.yaml

  - emby.yaml
  - flood.yaml
  - jackett.yaml
  - jellyfin.yaml
  - jellyseerr.yaml
  - plex.yaml
  - qbittorrent.yaml
  - radarr.yaml
  - sonarr.yaml
