---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - downloads-data.yaml
  - downloads.yaml
  - family-pomaz.yaml
  - kids-movies.yaml
  - kids-tv.yaml
  - movies.yaml
  - music-sound.yaml
  - music-video.yaml
  - tv.yaml

  # - emby.yaml
  # - flood.yaml
  # - jackett.yaml
  # - jellyseerr.yaml
  # - jellyfin.yaml
  # - plex.yaml
  # - radarr.yaml
  # - sonarr.yaml

