---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-video
spec:
  storageClassName: music-video
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.${SECRET_DOMAIN}
    path: "/media/media/music/video"
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-video
spec:
  storageClassName: music-video
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
