---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv
spec:
  storageClassName: tv
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.2
    path: "/mnt/data/media/tv"
  mountOptions:
    - vers=4.2
    - rsize=1048576
    - wsize=1048576
    - async
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv
spec:
  storageClassName: tv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
