---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-db-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secret-manager
  target:
    name: auth-db-secrets
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      data:
        username: "{{ .APP_USER }}"
        password: "{{ .APP_PASSWORD }}"
  dataFrom:
    - extract:
        key: auth-cluster-secrets
