---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-cluster-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secret-manager
  target:
    name: auth-cluster-secrets
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: auth-secrets
