# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/secretstore_v1.json
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: immich-k8s-local-store
spec:
  provider:
    kubernetes:
      remoteNamespace: immich
      auth:
        serviceAccount:
          name: immich-secrets-reader
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt