---
# yaml-language-server: $schema=https://schemas.gallay.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - service-account.yaml
  - k8s-local-store.yaml