# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.35.1-standalone-strict/role.json
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: immich-secrets-reader
  namespace: immich
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.35.1-standalone-strict/rolebinding.json
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: immich-secrets-reader
  namespace: immich
subjects:
  - kind: ServiceAccount
    name: immich-secrets-reader
roleRef:
  kind: Role
  name: immich-secrets-reader
  apiGroup: rbac.authorization.k8s.io