# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: ${APP}
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
  uninstall:
    keepHistory: false
  values:
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            runAsNonRoot: true
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: OnRootMismatch
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/pocket-id/pocket-id
              tag: v2.0.2
            env:
              TZ: "Europe/Budapest"
              ANALYTICS_DISABLED: true
              APP_URL: https://auth.${SECRET_DOMAIN}
              DB_PROVIDER: postgres
              DB_CONNECTION_STRING_FILE: /var/secrets/db/connection-string
              ENCRYPTION_KEY_FILE: /var/secrets/encryption/key
              INTERNAL_APP_URL: http://${APP}.auth.svc.cluster.local:${PORT}
              LOG_JSON: "true"
              PORT: ${PORT}
              PGID: ${APP_GID}
              PUID: ${APP_UID}
              TRUST_PROXY: "true"
              SMTP_TLS: "${SMTP_TLS}"
              SMTP_HOST: "${SMTP_HOST}"
              SMTP_PORT: "${SMTP_PORT}"
              SMTP_FROM: "${SMTP_FROM}"
              SMTP_PASSWORD: "${SMTP_PASSWORD}"
              SMTP_USER: "${SMTP_USER}"
              UI_CONFIG_DISABLED: "true"
              APP_NAME: "Gallay.HU"
              EMAILS_VERIFIED: "true"
              ALLOW_OWN_ACCOUNT_EDIT: "false"
              EMAIL_LOGIN_NOTIFICATION_ENABLED: "true"
              EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED: "true"
              EMAIL_API_KEY_EXPIRATION_ENABLED: "true"
              EMAIL_ONE_TIME_ACCESS_AS_UNAUTHENTICATED_ENABLED: "true"
              TRACING_ENABLED: "true"
              METRICS_ENABLED: "true"
              OTEL_METRICS_EXPORTER: prometheus
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    service:
      app:
        type: LoadBalancer
        ports:
          http:
            port: ${PORT}
            protocol: TCP

    serviceMonitor:
      app:
        endpoints:
          - port: http
    route:
      app:
        hostnames: ["auth", "auth.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: ${PORT}
    # yaml-language-server: $schema=https://github.com/bjw-s-labs/helm-charts/raw/9eb6d448787f8a83e500d20c62b7a22e9dacbc67/charts/library/common/values.schema.json
    persistence:
      db-connection-string:
        enabled: true
        type: secret
        name: postgres-app
        items:
          - key: fqdn-uri
            path: connection-string
        advancedMounts:
          app:
            app:
              - path: /var/secrets/db
      encryption-key:
        enabled: true
        type: secret
        name: auth-cluster-secrets
        items:
          - key: SECRET_KEY
            path: key
        advancedMounts:
          app:
            app:
              - path: /var/secrets/encryption
      app-data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
        advancedMounts:
          app:
            app:
              - path: /app/data
                readOnly: false
