---
# ConfigMap for driver configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: truenas-csi-config
data:
  truenasURL: "wss://nas.${SECRET_DOMAIN}/api/current"
  truenasInsecure: "true"  # Set to "true" for self-signed certificates, "false" or remove for valid certs
  defaultPool: "data/truenas-csi/volumes"
  nfsServer: "nas.${SECRET_DOMAIN}"
  iscsiPortal: "nas.${SECRET_DOMAIN}:3260"
