---
# yaml-language-server: $schema=https://schemas.gallay.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app publish-k8s-schemas
  namespace: &ns jobs
spec:
  targetNamespace: *ns
  path: ./kubernetes/apps/jobs/publish-k8s-schemas/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      APP_UID: "65534"
      APP_GID: "65533"
  interval: 1h
  prune: true
  wait: false
  timeout: 5m
