---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
components:
  - ../../components/common
resources:
  - ./secrets/ks.yaml
  # - ./database/ks.yaml
  - ./persistent-volume-claims/ks.yaml
