---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  instances: 2
  primaryUpdateStrategy: supervised
  storage:
    size: 30Gi
    storageClass: ceph-block
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser
  monitoring:
    enablePodMonitor: true
  backup:
    target: primary
    volumeSnapshot:
      online: true
      snapshotOwnerReference: none
      className: iscsi
      walClassName: iscsi
    retentionPolicy: 7d
