---
# yaml-language-server: $schema=https://schemas.gallay.io/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  instances: 3
  primaryUpdateStrategy: supervised
  storage:
    size: 50Gi
    storageClass: iscsi
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 7d
    target: primary
    volumeSnapshot:
      labels:
        app.kubernetes.io/name: auth-cluster-db-backup
      online: true
      onlineConfiguration:
        waitForArchive: true
        immediateCheckpoint: true
      className: iscsi
      walClassName: iscsi
