---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secrets.yaml
  - ./cluster.yaml
  # - ./prometheus-rule.yaml
  - ./service.yaml
  - ./daily-backup.yaml