---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-assistant
  namespace: &namespace home-assistant
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/home-assistant/home-assistant/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: external-secrets
      namespace: secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: mosquitto
      namespace: home-assistant
  components: []
  postBuild:
    substitute:
      APP: *app
      APP_UID: "65534"
      APP_GID: "65533"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
