# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.35.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:u0YIklwWWjID3QS5mV4CnKPCHoADTWMFhBPjs/3wHdHfVyyW7djlRBb3OeEYSf1fSgRMqTSUwTygKsPk6ewS6/Pd+BiE82MqTGh7SbFZ32quNYGatTO4IO+JCNO6aJT3o4HJSDnBMMiutraNyAx1C/AcuIkRM8A6bOkuGa+3sBxHjWLw48i8I4bthrtAc7AvATEPA84ZmsyDIZw12e4lzjDya40Qw5ZcxNdbUK7DkdkXjMbL,iv:8TyCiSgy1tEQDHYjBEpbAhcgwPtBch/sceKiqJll4xo=,tag:uuioIPPZhK2fiXuAqRInuQ==,type:str]
sops:
  age:
    - recipient: age17kkjwh97ech8ky6sa05xnyuxr9gpqwdjq8wjqc55a2mu7mdv9s8qvdfxpv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNWVEOUl0Q243VThiYnFj
        TmcvSUdEMm5OK0JDSGhCZzJTMUhQZkZucURNCjdzMUlGdzFndjNMa2FVZGN2RW5N
        SHB3Z3ZybTgrTXpnMDE1R3RmbmZGUEkKLS0tIHdyZUkzYjFDMU9lakdHV2lsRzdk
        eEVPQUdxbzlhTVBCektYZ2pTQlFpWTQKQ+jA/RrgF+I1IGa38H1788YtvAfZoAng
        LC5MSrm0Zg7/M5iNWLDssO0dOrhuafWr+q38ZeEH9YzeCN71g+KW5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-02T07:07:13Z"
  mac: ENC[AES256_GCM,data:TX1J2H5MsuwHwKO5K+O4zBUw9Hf55Qgy5O5uaus3CLGtoC7vL0xZw1eLxnDp5/B1dHu91nDn6frn6MYmJL79cpkzONJE8iBYgmjCbeVbEKSFbsQ5+8I33y+lTyPJgwgvuI73KizHeBTL4M+Sm9uvxPhR2JmnTBZfzezyjzQCqk8=,iv:+WFTLIQCjELvK0myfdvXKDHMR7x5wgtUXLvgnv76Cek=,tag:0RHISdixMnMilKs/LcuiXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
