---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser
type: basic-auth
stringData:
  username: ${POSTGRES_SUPER_USER}
  password: ${POSTGRES_SUPER_PASS}
  POSTGRES_SUPER_USER: ${POSTGRES_SUPER_USER}
  POSTGRES_SUPER_PASS: ${POSTGRES_SUPER_PASS}
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-user
type: basic-auth
stringData:
  username: ${IMMICH_USERNAME}
  password: ${IMMICH_PASSWORD}
