---
# yaml-language-server: $schema=https://schemas.gallay.io/dragonflydb.io/dragonfly_v1alpha1.json

apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly-cluster
spec:
  replicas: 2
  authentication:
    passwordFromSecret:
      key: password
      name: dragonfly-access
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 600m
      memory: 1Gi