---
web:
  port: ${CUSTOM_WEB_PORT}
storage:
  type: sqlite
  path: /config/sqlite.db
  caching: true
metrics: true
debug: false
default-external-web: &default-external-web
  group: external
  interval: 1m
  ui:
    hide-hostname: true
    hide-url: true
  client:
    dns-resolver: tcp://1.1.1.1:53
  conditions:
    - "len([BODY]) > 0"
default-internal-web: &default-internal-web
  group: internal
  interval: 1m
  ui:
    hide-hostname: true
    hide-url: true
  client:
    dns-resolver: tcp://192.168.0.99:53
  conditions:
    - "len([BODY]) > 0"
ui:
  title: Status | Gatus
  header: Status
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: status
    group: guarded
    url: 1.1.1.1
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    dns:
      query-name: "status.${SECRET_DOMAIN}"
      query-type: A
    conditions:
      - "len([BODY]) == 0"


  - name: emby
    <<: *default-internal-web
    url: https://emby.${SECRET_DOMAIN}

  - name: plex
    <<: *default-internal-web
    url: https://plex.${SECRET_DOMAIN}

  - name: qui
    <<: *default-internal-web
    url: https://qui.${SECRET_DOMAIN}

  - name: jackett
    <<: *default-internal-web
    url: https://jackett.${SECRET_DOMAIN}

  - name: jellyseerr
    <<: *default-internal-web
    url: https://jellyseerr.${SECRET_DOMAIN}

  - name: radarr
    <<: *default-internal-web
    url: https://radarr.${SECRET_DOMAIN}

  - name: sonarr
    <<: *default-internal-web
    url: https://sonarr.${SECRET_DOMAIN}


  - name: auth
    <<: *default-external-web
    url: https://auth.${SECRET_DOMAIN}

  - name: emby
    <<: *default-external-web
    url: https://emby.${SECRET_DOMAIN}

  - name: flux-webhook
    <<: *default-external-web
    url: https://flux-webhook.${SECRET_DOMAIN}
    conditions:
      - "[STATUS] == 404"

  - name: plex
    <<: *default-external-web
    url: https://plex.${SECRET_DOMAIN}

  - name: sonarr
    <<: *default-external-web
    url: https://sonarr.${SECRET_DOMAIN}

  - name: radarr
    <<: *default-external-web
    url: https://radarr.${SECRET_DOMAIN}
