---
web:
  port: ${CUSTOM_WEB_PORT}
storage:
  type: sqlite
  path: /config/sqlite.db
  caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: status
    group: guarded
    url: 1.1.1.1
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    dns:
      query-name: "status.${SECRET_DOMAIN}"
      query-type: A
    conditions:
      - "len([BODY]) == 0"

  - name: auth
    group: external
    url: https://auth.${SECRET_DOMAIN}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "len([BODY]) > 0"


  - name: emby
    group: external
    url: https://emby.${SECRET_DOMAIN}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "len([BODY]) > 0"


  - name: plex
    group: external
    url: https://plex.${SECRET_DOMAIN}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "len([BODY]) > 0"



  - name: qui
    group: internal
    url: https://qui.${SECRET_DOMAIN}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://192.168.0.99:53
    conditions:
      - "len([BODY]) > 0"



  - name: jackett
    group: internal
    url: https://jackett.${SECRET_DOMAIN}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://192.168.0.99:53
    conditions:
      - "len([BODY]) > 0"


  - name: jellyseerr
    group: internal
    url: https://jellyseerr.${SECRET_DOMAIN}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://192.168.0.99:53
    conditions:
      - "len([BODY]) > 0"


  - name: radarr
    group: internal
    url: https://radarr.${SECRET_DOMAIN}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://192.168.0.99:53
    conditions:
      - "len([BODY]) > 0"

  - name: radarr
    group: external
    url: https://radarr.${SECRET_DOMAIN}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "len([BODY]) > 0"

  - name: sonarr
    group: internal
    url: https://sonarr.${SECRET_DOMAIN}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://192.168.0.99:53
    conditions:
      - "len([BODY]) > 0"

  - name: sonarr
    group: external
    url: https://sonarr.${SECRET_DOMAIN}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "len([BODY]) > 0"

  - name: flux-webhook
    group: external
    url: https://flux-webhook.${SECRET_DOMAIN}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
