# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.35.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ATqldBj+L+jbvENLMr2LbPIyIxgzckeF/fQ9k2DiRTS26mKAJd2sCA==,iv:RcQQGxsAVx3JsJVuzijwy5hS7VnIRZ4e0AsmTvhxTOM=,tag:hK/hsMB2+eL/lyDMpXAGuA==,type:str]
sops:
  age:
    - recipient: age17kkjwh97ech8ky6sa05xnyuxr9gpqwdjq8wjqc55a2mu7mdv9s8qvdfxpv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYmFROUViWDMwODlaRlAr
        WExLYldZT2N1VGdhS0tMNWx0Z0RaR094YlNvClRhTklZanJmd3pEOTZ1RjBhM3hW
        VVF5N29pVFVPUjJuUHRSUmVVd29DMk0KLS0tIE1TdU0rODlpMEpCK0VabThiWENx
        OC8veWYxRHY4cWVmeEpFQjlpQndXLzQKSzm7bz7I5z3Ml91kgH14XqllTdYJmWqM
        C6asH4Z3OuZOf+IZ0jGmjlGKGPMGiCguLDTmXwLYUG/e/3HE92Gh6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-02T07:07:13Z"
  mac: ENC[AES256_GCM,data:nydEU6nZz+QWt8CPc73Dv7gnaPciFIb5B/mOd19IjPEKiZ9bjw8RFNhCRVAtJJ2Z/PBMECW06jn8WTOkSioC7BN5Cc68nZpHIpTUXTBeUMndp9cOMQUC9E8vG+FkpD7WX6vV05PrxN3nW6N3r7KhON32FHtj26t/yWQWAUUlQb4=,iv:4XgMWQrLcr0HCNwEpEMAw70hAmewz19uaGTqFKY4jkw=,tag:NY8h3shtE79jCI8oQcYGqw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
