---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-secrets
  namespace: &namespace secrets
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  interval: 1h
  path: ./kubernetes/apps/secrets/external-secrets/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false

# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app bitwarden-certificates
#   namespace: &namespace secrets
# spec:
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   healthChecks:
#     - apiVersion: helm.toolkit.fluxcd.io/v2
#       kind: HelmRelease
#       name: *app
#       namespace: *namespace
#   interval: 1h
#   path: ./kubernetes/apps/secrets/external-secrets/bitwarden-certificates
#   postBuild:
#     substituteFrom:
#       - name: cluster-secrets
#         kind: Secret
#   prune: true
#   retryInterval: 2m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   dependsOn:
#     - name: cert-manager
#       namespace: cert-manager
#   targetNamespace: *namespace
#   timeout: 5m
#   wait: false

# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app secret-stores
#   namespace: &namespace secrets
# spec:
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   healthChecks:
#     - apiVersion: helm.toolkit.fluxcd.io/v2
#       kind: HelmRelease
#       name: *app
#       namespace: *namespace
#   interval: 1h
#   path: ./kubernetes/apps/secrets/external-secrets/secret-stores
#   postBuild:
#     substituteFrom:
#       - name: cluster-secrets
#         kind: Secret
#   dependsOn:
#     - name: external-secrets
#       namespace: secrets
#     - name: bitwarden-certificates
#       namespace: secrets
#   prune: true
#   retryInterval: 2m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   targetNamespace: *namespace
#   timeout: 5m
#   wait: false
