# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.1:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.1"
  - "homelab.gallay.hu"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:

  - hostname: "avarath"
    controlPlane: true
    ipAddress: "192.168.20.1"
    installDisk: "/dev/nvme1n1"
    # machineSpec:
    #   secureboot: false
    talosImageURL: factory.talos.dev/installer/e0b22154f4081cfac269b2a99c5dfe8f813408ab45b3394f5a7f7f944488f59f
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:72:00:f3"
        dhcp: false
        mtu: 9000
        addresses:
          - "192.168.20.1/16"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        vip:
          ip: "192.168.1.1"

  - hostname: "hummianet"
    controlPlane: true
    ipAddress: "192.168.20.2"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer/e0b22154f4081cfac269b2a99c5dfe8f813408ab45b3394f5a7f7f944488f59f
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:e0:4c:68:02:a0"
        dhcp: false
        mtu: 9000
        addresses:
          - "192.168.20.2/16"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        vip:
          ip: "192.168.1.1"

  - hostname: "esutha"
    controlPlane: true
    ipAddress: "192.168.20.3"
    installDisk: "/dev/sda"
    # machineSpec:
    #   secureboot: false
    talosImageURL: factory.talos.dev/installer/e12a0c3836e6b87585bb152e4dffc856a640868f297fc72bab227a513e8ecbc2
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "38:05:25:35:60:ee"
        dhcp: false
        mtu: 9000
        vip:
          ip: "192.168.1.1"
        addresses:
          - "192.168.20.3/16"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

