# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.1:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.1"
  - "homelab.gallay.hu"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  # - hostname: "arriron"
  #   controlPlane: true
  #   ipAddress: "192.168.10.1"
  #   installDisk: "/dev/nvme0n1"
  #   # machineSpec:
  #   #   secureboot: false
  #   talosImageURL: ghcr.io/talos-rpi5/installer
  #   networkInterfaces:
  #     - deviceSelector:
  #         hardwareAddr: "2c:cf:67:da:3b:96"
  #       dhcp: false
  #       vip:
  #         ip: "192.168.1.1"
  #       addresses:
  #         - "192.168.10.1/16"
  #       routes:
  #         - network: "0.0.0.0/0"
  #           gateway: "192.168.0.1"
  #       mtu: 1500

  - hostname: "widagoth"
    controlPlane: true
    ipAddress: "192.168.10.2"
    installDisk: "/dev/nvme0n1"
    # machineSpec:
    #   secureboot: false
    talosImageURL: ghcr.io/talos-rpi5/installer
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "2c:cf:67:da:3a:ee"
        dhcp: false
        vip:
          ip: "192.168.1.1"
        addresses:
          - "192.168.10.2/16"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500

  - hostname: "avarath"
    controlPlane: true
    ipAddress: "192.168.20.1"
    installDisk: "/dev/nvme1n1"
    # machineSpec:
    #   secureboot: false
    talosImageURL: factory.talos.dev/installer/9c1d1b442d73f96dcd04e81463eb20000ab014062d22e1b083e1773336bc1dd5
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:72:00:f3"
        dhcp: false
        addresses:
          - "192.168.20.1/16"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
        vip:
          ip: "192.168.1.1"

  - hostname: "hummianet"
    controlPlane: true
    ipAddress: "192.168.20.2"
    installDisk: "/dev/nvme0n1"

    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer/9c1d1b442d73f96dcd04e81463eb20000ab014062d22e1b083e1773336bc1dd5
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:e0:4c:68:02:a0"
        dhcp: false
        addresses:
          - "192.168.20.2/16"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
        vip:
          ip: "192.168.1.1"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

