---
# yaml-language-server: $schema=https://schemas.gallay.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-secrets
  namespace: &namespace immich
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/immich/immich/secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: external-secrets
      namespace: secrets
    - name: external-secrets
      namespace: immich
    - name: dragonfly-cluster
      namespace: immich
    - name: postgres-cluster
      namespace: immich
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: immich-secrets
        kind: Secret
    substitute:
      APP: *app
      APP_UID: "3001"
      APP_GID: "3001"
  prune: true
  wait: false
  interval: 30m
  timeout: 5m

---
# yaml-language-server: $schema=https://schemas.gallay.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: &namespace immich
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/immich/immich/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: external-secrets
      namespace: secrets
    - name: persistent-volume-claims
      namespace: immich
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: composed-secret
        kind: Secret
    substitute:
      APP: *app
      APP_UID: "3001"
      APP_GID: "3001"
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
