---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cluster
  namespace: &namespace immich
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/immich/database/postgres-cluster
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: immich-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  dependsOn:
    - name: external-secrets
      namespace: immich
    - name: democratic-csi
      namespace: system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false

