---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sonarr
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/media/sonarr/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: external-secrets
      namespace: secrets
    - name: cluster
      namespace: media
    - name: secrets
      namespace: media
    - name: persistent-volume-claims
      namespace: media
    - name: config
      namespace: media
  components: []
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: media-cluster-secrets
        kind: Secret
      - name: media-config
        kind: ConfigMap
    substitute:
      APP: *app
      APP_UID: "1000"
      APP_GID: "1000"
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
