---
# CSI Driver object
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.truenas.io
spec:
  attachRequired: true
  podInfoOnMount: true
  fsGroupPolicy: File
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
