---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.35.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser
type: basic-auth
stringData:
  username: ${POSTGRES_SUPER_USER}
  password: ${POSTGRES_SUPER_PASS}
  POSTGRES_SUPER_USER: ${POSTGRES_SUPER_USER}
  POSTGRES_SUPER_PASS: ${POSTGRES_SUPER_PASS}
