---
apiVersion: akproxy.goauthentik.io/v1
kind: ProxyProvider
metadata:
  name: echo
  namespace: default
spec:
  name: echo
  externalHost: "https://echo.${SECRET_DOMAIN}"
  mode: forward_single
  authentication_flow: default-authentication-flow
  authorization_flow: default-provider-authorization-implicit-consent
