---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tns-csi-driver
  install:
    remediation:
      retries: 0
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    truenas:
      skipTLSVerify: true
      url: wss://nas.${SECRET_DOMAIN}:443/api/current
      apiKey: ${ADMIN_API_KEY}
    namespace: storage
    snapshots:
      enabled: true
      volumeSnapshotClass:
        create: true
        deletionPolicy: Delete

      detached:
        enabled: true
        parentDataset: "${SNAPSHOTS_PATH}"
        deletionPolicy: Delete
    storageClasses:
      nfs:
        enabled: true
        pool: data
        server: nas.${SECRET_DOMAIN}
        path: "${DATA_SET_PATH}"
      iscsi:
        enabled: true
        name: tns-csi-iscsi
        pool: nas.${SECRET_DOMAIN}
        parentDataset: "${DATA_SET_PATH}"
        encryption: "true"
