# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: ${APP}
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            runAsNonRoot: true
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          copy-opt:
            image:
              repository: &repo quay.io/keycloak/keycloak
              tag: &version 26.4.6
            # imagePullPolicy: IfNotPresent
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
            command: ["sh", "-c"]
            args:
              - "mkdir -p /tmp/opt/keycloak && cp -R /opt/keycloak/* /tmp/opt/keycloak/"
          build:
            dependsOn:
              - copy-opt
            image:
              repository: *repo
              tag: *version
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
            command:
              - /opt/keycloak/bin/kc.sh
              - build
              - --http-enabled=true
        containers:
          main:
            image:
              repository: *repo
              tag: *version
            command:
              - /opt/keycloak/bin/kc.sh
              - start
              - --proxy-headers=xforwarded
              - --http-enabled=true
              - --optimized
            env:
              KC_HEALTH_ENABLED: "true"
              KC_METRICS_ENABLED: "true"
              KC_DB: postgres
              KC_DB_URL_HOST:
                secretKeyRef:
                  name: postgres-app
                  key: host
              KC_DB_URL:
                secretKeyRef:
                  name: postgres-app
                  key: fqdn-jdbc-uri
              KC_BOOTSTRAP_ADMIN_USERNAME: admin
              KC_BOOTSTRAP_ADMIN_PASSWORD:
                secretKeyRef:
                  name: admin-secret
                  key: ADMIN_PASSWORD
              KC_HOSTNAME: ${APP}.${SECRET_DOMAIN}
              KC_HTTP_RELATIVE_PATH: /
              KC_PROXY: edge
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            port: 8080
            protocol: TCP
    route:
      internal:
        hostnames: ["${APP}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs: [{}]
    persistence:
      temp:
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /tmp
                readOnly: false
      keycloak-data:
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /opt/keycloak/data
                readOnly: false
      workspace:
        type: emptyDir
        advancedMounts:
          main:
            copy-opt:
              - path: /tmp/opt
                readOnly: false
            build:
              - path: /opt
                readOnly: false
            main:
              - path: /opt
                readOnly: false
    #   config:
    #     type: persistentVolumeClaim
    #     existingClaim: jackett
    #     advancedMounts:
    #       main:
    #         main:
    #           - path: /config
    #             readOnly: false

