---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authelia
  namespace: &namespace auth
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets
      namespace: secrets
    - name: authelia-db
      namespace: auth
    - name: secrets
      namespace: auth

  interval: 1h
  path: ./kubernetes/apps/auth/authelia/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: auth-cluster-secrets
        kind: Secret
    substitute:
      APP: authelia
      APP_UID: "1000"
      APP_GID: "1000"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
