apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: oidc-auth
spec:
  # Target specific services or use nodeSelector
  services:
    - name: echo
      namespace: default
  resources:
    - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
      name: oidc-auth-listener
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: oidc_auth
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: original-destination
                http_filters:
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      transport_api_version: V3
                      http_service:
                        server_uri:
                          uri: http://authentik-outpost.authentik.svc.cluster.local:9000
                          cluster: authentik-outpost
                        timeout: 10s
                        authorization_request:
                          allowed_headers:
                            patterns:
                              - exact: cookie
                              - exact: authorization
                              - exact: x-authentik-email
                              - exact: x-authentik-groups
                              - exact: x-authentik-name
                              - exact: x-authentik-uid
                        authorization_response:
                          allowed_upstream_headers:
                            patterns:
                              - exact: x-authentik-email
                              - exact: x-authentik-groups
                              - exact: x-authentik-name
                              - exact: x-authentik-uid
                          allowed_client_headers:
                            patterns:
                              - exact: set-cookie
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      name: authentik-outpost
      connect_timeout: 10s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: authentik-outpost
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: authentik-outpost.authentik.svc.cluster.local
                      port_value: 9000