---
# yaml-language-server: $schema=https://schemas.gallay.io/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ${APP}
spec:
  interval: 1h
  url: https://charts.goauthentik.io
