---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres-db
spec:
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql versioning=redhat
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  instances: 2
  primaryUpdateStrategy: supervised
  storage:
    size: 30Gi
    storageClass: nfs-dynamic
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser
  managed:
    roles:
      - connectionLimit: -1
        ensure: present
        name: "${AUTHELIA_USER}"
        comment: Authelia app user
        inherit: false
        login: true
        superuser: false
        createdb: false
        passwordSecret:
          name: authelia-user
  postgresql:
    synchronous:
      method: any
      number: 1
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  probes:
    startup:
      type: streaming
      maximumLag: 32Mi
      periodSeconds: 5
      failureThreshold: 120
    readiness:
      type: streaming
      maximumLag: 0
      periodSeconds: 10
      failureThreshold: 6