---
# yaml-language-server: $schema=http://schemas.home.local/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-production"
spec:
  secretName: "${SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames: ["${SECRET_DOMAIN}", "*.${SECRET_DOMAIN}"]

# ---
# # yaml-language-server: $schema=http://schemas.home.local/cert-manager.io/certificate_v1.json
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: "gallay-io-production"
# spec:
#   secretName: "gallay-io-production-tls"
#   issuerRef:
#     name: letsencrypt-production
#     kind: ClusterIssuer
#   commonName: "gallay.io"
#   dnsNames: ["gallay.io", "*.gallay.io"]
