---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-dns
  annotations:
    external-dns.alpha.kubernetes.io/target: "internal-dns.gallay.io"
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: "192.168.1.101"
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "internal-dns.gallay.io"
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.gallay.io"
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.gallay.io"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: gallay-io-production-tls
