---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: sonoff-zigbee-device
spec:
  rules:
    - # Google Coral USB Accelerator
      name: sonoff-zigbee-device
      labels:
        feature.node.kubernetes.io/amd-gpu: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: { op: In, value: ["1002"] }
